# HtcOneM8Pkg CI build on VSTS

trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo apt update 
  displayName: 'Update APT sources'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    architecture: 'x64'
  displayName: Install correct Python

- script:  sudo apt -y install build-essential uuid-dev iasl git nasm python3-distutils crossbuild-essential-armel skales gcc-arm-linux-gnueabihf gcc-arm-none-eabi mkbootimg
  displayName: 'Install VSTS dependencies'

- script: sudo ln -sfn $(pwd) ../HtcOneM8Pkg
  displayName: Fix directory links

- script: |
      cd /home/vsts/work/1/
      git clone https://github.com/Tianocore/edk2.git --recursive --depth=1
      git clone https://github.com/tianocore/edk2-platforms.git --depth=1
  displayName: Clone sources

- script:  |
      cd /home/vsts/work/1/edk2
      make -C BaseTools/
  displayName: Build BaseTools

- script: |
      cd /home/vsts/work/1/HtcOneM8Pkg
      export PACKAGES_PATH=$PWD/home/vsts/work/1/edk2:$PWD/home/vsts/work/1/edk2-platforms:$PWD
      export WORKSPACE=$PWD/workspace
      . /home/vsts/work/1/edk2/edksetup.sh
      chmod a+x *.sh

- script: |
    ./build.sh -d OneM8
  displayName: Build uefi for all platforms

- task: PublishBuildArtifacts@1
  displayName: 'Publish Htc One M8 UEFI payload'
  inputs: 
    pathtoPublish: /home/vsts/work/1/HtcOneM8Pkg/ImageResources/HtcOneM8/bootpayload.bin
    artifactName: Htc One M8 UEFI payload

- task: PublishBuildArtifacts@1
  displayName: 'Publish Htc One M8 UEFI payload'
  inputs: 
    pathtoPublish: /home/vsts/work/1/HtcOneM8Pkg/ImageResources/HtcOneM8/uefi.img
    artifactName: Htc One M8 UEFI kernel

- task: PublishBuildArtifacts@1
  displayName: 'Publish Htc One M8 UEFI payload'
  inputs: 
    pathtoPublish: /home/vsts/work/1/HtcOneM8Pkg/ImageResources/HtcOneM8/emmc_appsboot.mbn
    artifactName: Htc One M8 UEFI elf

