# SoC Drivers binaries
  INF MSM8974Pkg/QcomDrivers/EnvDxe/EnvDxe.inf
  INF MSM8974Pkg/QcomDrivers/TLMMDxe/TLMMDxe.inf
  INF MSM8974Pkg/QcomDrivers/SmemDxe/SmemDxe.inf
  INF MSM8974Pkg/QcomDrivers/ChipInfoDxe/ChipInfoDxe.inf
  INF MSM8974Pkg/QcomDrivers/SmdDxe/SmdDxe.inf

  # INF MSM8974Pkg/QcomDrivers/TzDxe/TzDxe.inf
  INF MSM8974Pkg/QcomDrivers/DALSYSDxe/DALSYSDxe.inf
  # INF MSM8974Pkg/QcomDrivers/ClockDxe/ClockDxe.inf #(seems to hang)
  # INF MSM8974Pkg/hTCPkg/HardwareInitDxe/HardwareInitDxe.inf
  
  # INF MSM8974Pkg/QcomDrivers/HWIODxe/HWIODxe.inf
  INF MSM8974Pkg/QcomDrivers/I2CDxe/I2CDxe.inf
  INF MSM8974Pkg/QcomDrivers/SPIDxe/SPIDxe.inf
  INF MSM8974Pkg/QcomDrivers/SPMIDxe/SPMIDxe.inf
  INF MSM8974Pkg/QcomDrivers/MMCHSDxe/MMCHSDxe.inf
  
  # INF MSM8974Pkg/QcomDrivers/DisplayDxe/DisplayDxe.inf # hopefully soon
  INF MSM8974Pkg/Drivers/SimpleFbDxe/SimpleFbDxe.inf
  INF MSM8974Pkg/QcomDrivers/PlatformInfoDxe/PlatformInfoDxe.inf
  INF MSM8974Pkg/QcomDrivers/ButtonsDxe/ButtonsDxe.inf
  INF MSM8974Pkg/QcomDrivers/PmicDxe/PmicDxe.inf
  # INF MSM8974Pkg/QcomDrivers/HashDxe/HashDxe.inf
  # INF MSM8974Pkg/QcomDrivers/RNGDxe/RngDxe.inf
  # INF MSM8974Pkg/QcomDrivers/TrEEDxe/TrEEDxe.inf