MSM8974Pkg/QcomDrivers/EnvDxe/EnvDxe.inf
  MSM8974Pkg/QcomDrivers/TLMMDxe/TLMMDxe.inf
  MSM8974Pkg/QcomDrivers/SmemDxe/SmemDxe.inf
  MSM8974Pkg/QcomDrivers/ChipInfoDxe/ChipInfoDxe.inf
  MSM8974Pkg/QcomDrivers/SmdDxe/SmdDxe.inf

  MSM8974Pkg/QcomDrivers/TzDxe/TzDxe.inf
  MSM8974Pkg/QcomDrivers/DALSYSDxe/DALSYSDxe.inf
  MSM8974Pkg/QcomDrivers/ClockDxe/ClockDxe.inf
  MSM8974Pkg/hTCPkg/HardwareInitDxe/HardwareInitDxe.inf

  MSM8974Pkg/QcomDrivers/HWIODxe/HWIODxe.inf
  MSM8974Pkg/QcomDrivers/I2CDxe/I2CDxe.inf
  MSM8974Pkg/QcomDrivers/SPIDxe/SPIDxe.inf
  MSM8974Pkg/QcomDrivers/SPMIDxe/SPMIDxe.inf
  MSM8974Pkg/QcomDrivers/MMCHSDxe/MMCHSDxe.inf

  MSM8974Pkg/QcomDrivers/DisplayDxe/DisplayDxe.inf
  MSM8974Pkg/QcomDrivers/PlatformInfoDxe/PlatformInfoDxe.inf
  MSM8974Pkg/QcomDrivers/ButtonsDxe/ButtonsDxe.inf
  MSM8974Pkg/QcomDrivers/PmicDxe/PmicDxe.inf
  MSM8974Pkg/hTCPkg/PartitionIODxe/PartitionIODxe.inf
  MSM8974Pkg/QcomDrivers/HashDxe/HashDxe.inf
  MSM8974Pkg/QcomDrivers/RNGDxe/RngDxe.inf
  MSM8974Pkg/QcomDrivers/TrEEDxe/TrEEDxe.inf