# SoC Drivers binaries
  INF QcomPkg/Drivers/EnvDxe/EnvDxe.inf
  INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
  INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
  INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
  INF QcomPkg/Drivers/SmdDxe/SmdDxe.inf

  # INF QcomPkg/Drivers/TzDxe/TzDxe.inf
  INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
  # INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf #(seems to hang)
  # INF hTCPkg/HardwareInitDxe/HardwareInitDxe.inf
  
  # INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
  INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
  INF QcomPkg/Drivers/SPIDxe/SPIDxe.inf
  INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
  INF QcomPkg/Drivers/MMCHSDxe/MMCHSDxe.inf
  
  # INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf # hopefully soon
  INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
  INF QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
  INF QcomPkg/Drivers/PmicDxe/PmicDxe.inf
  # INF QcomPkg/Drivers/HashDxe/HashDxe.inf
  # INF QcomPkg/Drivers/RNGDxe/RngDxe.inf
  # INF QcomPkg/Drivers/TrEEDxe/TrEEDxe.inf