QcomPkg/Drivers/EnvDxe/EnvDxe.inf
  QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
  QcomPkg/Drivers/SmemDxe/SmemDxe.inf
  QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
  QcomPkg/Drivers/SmdDxe/SmdDxe.inf

  QcomPkg/Drivers/TzDxe/TzDxe.inf
  QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
  QcomPkg/Drivers/ClockDxe/ClockDxe.inf
  hTCPkg/HardwareInitDxe/HardwareInitDxe.inf

  QcomPkg/Drivers/HWIODxe/HWIODxe.inf
  QcomPkg/Drivers/I2CDxe/I2CDxe.inf
  QcomPkg/Drivers/SPIDxe/SPIDxe.inf
  QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
  QcomPkg/Drivers/MMCHSDxe/MMCHSDxe.inf

  QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
  QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
  QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
  QcomPkg/Drivers/PmicDxe/PmicDxe.inf
  hTCPkg/PartitionIODxe/PartitionIODxe.inf
  QcomPkg/Drivers/HashDxe/HashDxe.inf
  QcomPkg/Drivers/RNGDxe/RngDxe.inf
  QcomPkg/Drivers/TrEEDxe/TrEEDxe.inf